execute: FPInsert.cpp FPNode.cpp FPTree.cpp cond_fp.cpp FPNode.h
	gcc -g FPInsert.cpp -O3 -o fptree -lstdc++ -std=c++11
# 	./execute "/media/col/60873db8-7b4c-4d3d-b719-eb0ca03010bf/jai/webdocs.dat" 30
	
