execute: FPInsert.cpp FPNode.cpp FPTree.cpp cond_fp.cpp FPNode.h
	gcc -g FPInsert.cpp  -o execute -lstdc++ 
run: execute
	./execute "./dattest.txt" 0
# 	./execute "/media/col/60873db8-7b4c-4d3d-b719-eb0ca03010bf/jai/webdocs.dat" 30
	