main: main.cpp
	gcc main.cpp -o main -lstdc++ -std=c++11

execute:
	./main input3 40 output.txt

mytest:	
	g++ test.cpp -o test
	./test input3 40
clear: 
	rm test




mytest1:	
	g++ test1.cpp -o test1
	./test1 input input1
	rm test1
cleartest1: 
	rm test1

mytest2:	
	g++ test2.cpp -o test2
	./test2
cleartest2: 
	rm test2

